[package]
name = "translator"
version = "0.1.0"
authors = ["Benoît Peccatte <benoit.peccatte@normation.com>"]
edition = "2018"

[dependencies]
nom = "5.*"
serde_json = "1.0"

[dependencies.nom_locate]
version = "^0.3"
path = "../nom_locate"

