version: "2"
services:
    cf_execd:
       read_only: true
       build:
         context: .
         dockerfile: cf-execd.Dockerfile
       volumes:
          - cfengine_community:/var/rudder/cfengine-community/
          - uuid_keys:/data
          - ncf:/var/rudder/ncf
          - shared:/var/rudder/share
          - secure_httpd:/opt/rudder/etc/ssl/
          - httpd_conf:/apache_conf_file
          - relay_conf:/opt/rudder/etc/relayd
          - nodelist:/var/rudder/lib/relay/
       tmpfs:
          - /var/rudder/tmp
          - /var/backup/rudder
          - /opt/rudder/var/fusioninventory
          - /var/rudder/inventories
       external_links:
          - server
    cf_serverd: 
       read_only: true
       build:
         context: .
         dockerfile: cf-serverd.Dockerfile
       volumes:
         - cfengine_community:/var/rudder/cfengine-community/
         - uuid_keys:/data:ro
         - ncf:/var/rudder/ncf:ro
         - shared:/var/rudder/share:ro
    relay:
       read_only: true
       build:
         context: .
         dockerfile: relay.Dockerfile
       volumes:
          - nodelist:/var/rudder/lib/relay:ro
          - relay_conf:/opt/rudder/etc/relayd:ro
       tmpfs:
          - /var/rudder/reports
          - /var/rudder/inventories
    httpd:
       build:
         context: .
         dockerfile: httpd.Dockerfile
       volumes:
          - httpd_conf:/apache_conf_file:ro
          - secure_httpd:/opt/rudder/etc/ssl:ro

volumes:
     cfengine_community:
     uuid_keys:
     ncf:
     shared:
     secure_httpd:
     httpd_conf:
     nodelist:
     relay_conf:
