version: "2"
services:
    cf_execd:
       stdin_open: true
       tty: true 
       build:
         context: .
         dockerfile: cf-execd.Dockerfile
       cap_add:
          - NET_ADMIN
       volumes:
          - rudder_config_files:/opt/rudder/etc
          - cfengine_community_files:/var/rudder/cfengine-community/
          - uuid_keys_files:/data
       tmpfs:
          - /var/rudder/tmp
          - /var/backup/rudder
          - /var/rudder/cfengine-community/state       
       external_links:
          - server                     
    cf_serverd: 
       build:
         context: .
         dockerfile: cf-serverd.Dockerfile
       cap_add:
         - NET_ADMIN
       volumes_from:
         - cf_execd:rw
       external_links:
          - server
       stdin_open: true
       tty: true
       read_only: true
volumes:
     rudder_config_files:
     cfengine_community_files:
     uuid_keys_files:
