version: "2"
services:
    cf_execd:
       read_only: true
       build:
         context: .
         dockerfile: cf-execd.Dockerfile
       volumes:
          - cfengine_community:/var/rudder/cfengine-community/
          - uuid_keys:/data
          - ncf:/var/rudder/ncf
          - shared:/var/rudder/share
       tmpfs:
          - /var/rudder/tmp
          - /var/backup/rudder
          - /opt/rudder/var/fusioninventory
          - /var/rudder/inventories
    cf_serverd: 
       read_only: true
       build:
         context: .
         dockerfile: cf-serverd.Dockerfile
       volumes:
         - cfengine_community:/var/rudder/cfengine-community/
         - uuid_keys:/data:ro
         - ncf:/var/rudder/ncf:ro
         - shared:/var/rudder/share:ro
volumes:
     cfengine_community:
     uuid_keys:
     ncf:
     shared:
