[workspace]
members = ["rudderc", "rudder-resource-type", "rudder-commons", "rudder-commons-test", "resource-types/*"]

[profile.dev]
# Disabling debug info speeds up builds a bunch,
# and we don't rely on it for debugging that much.
debug = 0

[profile.release]
strip = true
